### ISSUE TITLE
Female roosters and male hen

### ISSUE THREAD

**Issue by mazes-80** [runsy/petz#90]
I don't understand how it happens, is_male is well defined in petz/petz/chicken_mobkit.lua.
Somehow the variable is ignored later on, and it makes some weird things: "female roosters" and "male hen"

**Comment by runsy** [comment]
The issue was in "api_init_prop"

`self.is_male = mobkit.remember(self, "is_male", petz.set_random_gender())`

This assigned a random gender for each new petz, even for already defined genders as hens, roosters and elephants.

So I've introduced a nil check for is_male before assign or not a gender.

Solved in the last commit.

**Comment by mazes-80** [comment]
the commit fixed hen, but not rooster
I think there should be a:
`else`
`mobkit.remember(self, "is_male", self.is_male)`

**Comment by runsy** [comment]
Try the last one commit please.

**Comment by mazes-80** [comment]
Le Thu, 03 Feb 2022 14:42:58 -0800,
Juanchi Pro ***@***.***> a écrit :

> Try the last one commit please.
> 

Works for me
